
CREATE TABLE [dbo].[Members](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](15) NOT NULL,
	[Password] [nvarchar](128) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[FullName] [varchar](50) NOT NULL,
	[CreatedON] [smalldatetime] NOT NULL,
	[FromIP] [varchar](20) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_Members_UserId] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




CREATE TABLE [dbo].[Languages](
	[LangId] [varchar](6) NOT NULL,
	[Language] [nvarchar](50) NOT NULL,
	[Status] [tinyint] NOT NULL,
 CONSTRAINT [PK_Languages] PRIMARY KEY CLUSTERED 
(
	[LangId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




CREATE TABLE [dbo].[InputScripts](
	[ScriptId] [tinyint] IDENTITY(1,1) NOT NULL,
	[Script] [varchar](50) NOT NULL,
	[LocalName] [nvarchar](50) NULL,
 CONSTRAINT [PK_InputScripts] PRIMARY KEY CLUSTERED 
(
	[ScriptId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO





CREATE TABLE [dbo].[IScriptLangs](
	[ScriptId] [tinyint] NOT NULL,
	[LangId] [varchar](6) NOT NULL,
 CONSTRAINT [UK_IScriptLangs] UNIQUE NONCLUSTERED 
(
	[ScriptId] ASC,
	[LangId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



CREATE TABLE [dbo].[VKLs](
	[VKLId] [int] IDENTITY(1,1) NOT NULL,
	[LangCode] [varchar](6) NOT NULL,
	[Name] [varchar](25) NOT NULL,
	[Type] [tinyint] NOT NULL,
	[userId] [int] NOT NULL,
	[Visibility] [tinyint] NOT NULL,
 CONSTRAINT [PK_VKLs] PRIMARY KEY CLUSTERED 
(
	[VKLId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UK_VKLs_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC,
	[Type] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[VKLs]  WITH CHECK ADD  CONSTRAINT [FK__VKLs__LangCode__6FB49575] FOREIGN KEY([LangCode])
REFERENCES [dbo].[Languages] ([LangId])
GO

ALTER TABLE [dbo].[VKLs] CHECK CONSTRAINT [FK__VKLs__LangCode__6FB49575]
GO

ALTER TABLE [dbo].[VKLs]  WITH CHECK ADD  CONSTRAINT [FK__VKLs__userId__70A8B9AE] FOREIGN KEY([userId])
REFERENCES [dbo].[Members] ([UserId])
GO

ALTER TABLE [dbo].[VKLs] CHECK CONSTRAINT [FK__VKLs__userId__70A8B9AE]
GO

ALTER TABLE [dbo].[VKLs] ADD  CONSTRAINT [DF__VKLs__Type__719CDDE7]  DEFAULT ((0)) FOR [Type]
GO

ALTER TABLE [dbo].[VKLs] ADD  CONSTRAINT [DF__VKLs__Visibility__6EC0713C]  DEFAULT ((0)) FOR [Visibility]
GO


